version: "3.3"

services:
  snoop-rabbitmq:
    image: rabbitmq:3.7.3

  snoop-tika:
    image: logicalspark/docker-tikaserver

  search-pg:
    image: postgres:9.6
    volumes:
      - ./volumes/search-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: search
      POSTGRES_DATABASE: search

  search-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    volumes:
      - ./volumes/search-es/data:/usr/share/elasticsearch/data
      - ./volumes/search-es-snapshots:/opt/hoover/es-snapshots
    environment:
      discovery.type: single-node
      path.repo: /opt/hoover/es-snapshots

  ui:
    image: liquidinvestigations/hoover-ui:0.1
    volumes:
      - ./ui/build:/opt/hoover/ui/build

  search:
    image: liquidinvestigations/hoover-search:0.1.1
    volumes:
      - ./ui/build:/opt/hoover/ui/build
      - ./volumes/metrics:/opt/hoover/metrics
      - ./settings/search-settings.py:/opt/hoover/search/hoover/site/settings/local.py
      - ./settings/search-settings-testing.py:/opt/hoover/search/hoover/site/settings/testing_local.py
    depends_on:
      - search-pg
      - search-es
      - ui
    env_file:
      - ./settings/search.env
    ports:
      - "45024:80"
    environment:
      WAIT_HOSTS: search-es:9200, search-pg:5432
      WAIT_HOSTS_TIMEOUT: 60
